---
# This is a test only workflow which can be used to develop new workflows on git branches
# This workflow shall never be triggered automatically

name: Developer Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: Person to greet
        default: World
        required: true

jobs:
  greet:
    runs-on: [self-hosted, ubuntu-latest]
    outputs:
      job-status: ${{ job.status }}
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"

      - uses: actions/checkout@v3
