---
name: Reusable notify teams

on:
  workflow_call:
    inputs:
      successful:
        required: true
        type: boolean
    secrets:
      teams_alert_url:
        required: true
      teams_url:
        required: true

jobs:
  notify-teams:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Send notify
        env:
          SUCCESSFUL: ${{ inputs.successful }}
          WEBHOOK_ALERT_URL: ${{ secrets.teams_alert_url }}
          WEBHOOK_URL: ${{ secrets.teams_url }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          python3 ./infrastructure/bin/notify_teams.py
